[package]
name = "frontier-template-test-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Ethereum RPC (web3) compatibility layer for Substrate."
license = "GPL-3.0"

[dependencies]
sp-runtime = { path = "../../../vendor/substrate/primitives/runtime" }
sc-executor = { path = "../../../vendor/substrate/client/executor" }
sc-light = { path = "../../../vendor/substrate/client/light" }
substrate-test-client = { path = "../../../vendor/substrate/test-utils/client" }
frontier-template-runtime = { path = "../../runtime" }