version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Berlin
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
