[package]
name = "pallet-evm-precompile-modexp"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "MODEXP precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
num = { version = "0.4", default-features = false, features = ["alloc"] }

# frontier primitives
fp-evm = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	"num/std",
	# frontier primitives
	"fp-evm/std",
]
