[workspace]
members = [
	"frame/ethereum",
	"frame/evm",
	"client/consensus",
	"client/rpc-core",
	"client/rpc",
	"primitives/consensus",
	"primitives/evm",
	"primitives/rpc",
	"template/node",
	"template/runtime",
	"template/test-utils/client",
]