[workspace]
members = [
	"frame/ethereum",
	"frame/evm",
	"client/consensus",
	"primitives/consensus",
	"rpc",
	"rpc/core",
	"rpc/primitives",
	"template/node",
	"template/runtime",
	"template/test-utils/client",
]