[toolchain]
# Stable
#channel = "1.68.2" # rustc 1.68.2 (9eb3afe9e 2023-03-27)
# Nightly
channel = "nightly-2022-11-16" # rustc 1.67.0-nightly (a00f8ba7f 2022-11-15)
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
