[package]
name = "frontier-template-node"
version = "0.0.0"
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
edition = "2021"
license = "Unlicense"
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1"
clap = { version = "3.2", features = ["derive"] }
futures = "0.3.21"
log = "0.4.17"

# Parity
codec = { package = "parity-scale-codec", version = "3.1", features = ["derive"] }
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }

# Substrate
sc-basic-authorship = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-cli = { git = "https://github.com/humanode-network/substrate", branch = "master", features = ["wasmtime"] }
sc-client-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-consensus-aura = { git = "https://github.com/humanode-network/substrate", branch = "master", optional = true }
sc-consensus-manual-seal = { git = "https://github.com/humanode-network/substrate", branch = "master", optional = true }
sc-executor = { git = "https://github.com/humanode-network/substrate", branch = "master", features = ["wasmtime"] }
sc-finality-grandpa = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-keystore = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-network = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-rpc-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-service = { git = "https://github.com/humanode-network/substrate", branch = "master", features = ["wasmtime"] }
sc-telemetry = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-transaction-pool-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-consensus-aura = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-core = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-timestamp = { git = "https://github.com/humanode-network/substrate", branch = "master" }
# These dependencies are used for RPC
pallet-transaction-payment-rpc = { git = "https://github.com/humanode-network/substrate", branch = "master" }
substrate-frame-rpc-system = { git = "https://github.com/humanode-network/substrate", branch = "master" }
# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/humanode-network/substrate", branch = "master" }
frame-benchmarking-cli = { git = "https://github.com/humanode-network/substrate", branch = "master" }
frame-system = { git = "https://github.com/humanode-network/substrate", branch = "master" }
pallet-transaction-payment = { git = "https://github.com/humanode-network/substrate", branch = "master" }

# Frontier
fc-cli = { path = "../../client/cli" }
fc-consensus = { path = "../../client/consensus" }
fc-db = { path = "../../client/db" }
fc-mapping-sync = { path = "../../client/mapping-sync" }
fc-rpc = { path = "../../client/rpc" }
fc-rpc-core = { path = "../../client/rpc-core" }
fp-consensus = { path = "../../primitives/consensus" }
fp-dynamic-fee = { path = "../../primitives/dynamic-fee" }
fp-evm = { path = "../../primitives/evm" }
fp-rpc = { path = "../../primitives/rpc" }
fp-storage = { path = "../../primitives/storage" }

frontier-template-runtime = { path = "../runtime", default-features = false, features = ["std"] }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/humanode-network/substrate", branch = "master" }

[features]
default = ["aura", "with-rocksdb-weights"]
aura = [
	"sc-consensus-aura",
	"frontier-template-runtime/aura",
]
manual-seal = [
	"sc-consensus-manual-seal",
	"frontier-template-runtime/manual-seal",
]
with-rocksdb-weights = ["frontier-template-runtime/with-rocksdb-weights"]
with-paritydb-weights = ["frontier-template-runtime/with-paritydb-weights"]
rpc_binary_search_estimate = ["fc-rpc/rpc_binary_search_estimate"]
runtime-benchmarks = ["frontier-template-runtime/runtime-benchmarks"]
