[package]
name = "fp-self-contained"
version = "1.0.0-dev"
license = "Apache-2.0"
description = "Primitive Ethereum abstractions for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
ethereum = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, optional = true }

# substrate primitives
sp-runtime = { workspace = true }
# substrate frame
frame-support = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum/std",
	"scale-info/std",
	"serde",
	# substrate primitives
	"sp-runtime/std",
	# substrate frame
	"frame-support/std",
]
