[package]
name = "pallet-evm-chain-id"
version = "1.0.0-dev"
license = "Apache-2.0"
description = "EVM chain id storage pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

# Parity
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }

# Substrate FRAME
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	# Parity
	"codec/std",
	"scale-info/std",
	# Substrate FRAME
	"frame-support/std",
	"frame-system/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
