[package]
name = "pallet-evm-precompile-simple"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "Simple precompiles for EVM pallet."
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ripemd = { version = "0.1", default-features = false }

# substrate primitives
sp-io = { workspace = true }

# frontier primitives
fp-evm = { workspace = true }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	"ripemd/std",
	# substrate primitives
	"sp-io/std",
	# frontier primitives
	"fp-evm/std",
]
