[package]
name = "fc-db"
version = "2.0.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Frontier database backend"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1"
ethereum = { workspace = true, features = ["with-codec"] }
futures = "0.3.25"
log = "0.4.17"
parking_lot = "0.12.1"
smallvec = "1.10"
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.19", features = ["macros", "sync"] }

# Parity
kvdb-rocksdb = { workspace = true, optional = true }
parity-db = { workspace = true, optional = true }
scale-codec = { package = "parity-scale-codec", workspace = true }

# Substrate
sc-client-api = { workspace = true }
sc-client-db = { workspace = true, features = ["rocksdb"] }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true }
sp-database = { workspace = true }
sp-runtime = { workspace = true }
sp-storage = { workspace = true }

# Frontier
fc-storage = { workspace = true }
fp-consensus = { workspace = true, features = ["default"] }
fp-rpc = { workspace = true, features = ["default"] }
fp-storage = { workspace = true, features = ["default"] }

[features]
default = ["kvdb-rocksdb", "parity-db"]

[dev-dependencies]
fc-rpc = { workspace = true }
maplit = "1.0.2"
sc-block-builder = { workspace = true }
sp-consensus = { workspace = true }
substrate-test-runtime-client = { workspace = true }
tempfile = "3.3.0"
