[package]
name = "pallet-ethereum"
version = "4.0.0-dev"
license = "Apache-2.0"
description = "Ethereum compatibility full block processing emulation pallet for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
ethereum = { workspace = true }
ethereum-types = { workspace = true }
evm = { workspace = true }
rlp = { workspace = true }
scale-info = { workspace = true }

# substrate primitives
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
# substrate frame
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-timestamp = { workspace = true }

# frontier primitives
fp-consensus = { workspace = true }
fp-ethereum = { workspace = true }
fp-evm = { workspace = true }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true }
fp-storage = { workspace = true }
# frontier frame
pallet-evm = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
# Parity
libsecp256k1 = { version = "0.7", features = ["static-context", "hmac"] }
# Substrate
sp-core = { version = "7.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
# Substrate FRAME
pallet-balances = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum/std",
	"evm/std",
	"ethereum-types/std",
	"rlp/std",
	"scale-info/std",
	# substrate primitives
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	# substrate frame
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	# frontier primitives
	"fp-consensus/std",
	"fp-ethereum/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	"fp-storage/std",
	# frontier frame
	"pallet-evm/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-evm/try-runtime",
]
forbid-evm-reentrancy = ["pallet-evm/forbid-evm-reentrancy"]
