[package]
name = "pallet-evm-precompile-blake2"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "BLAKE2 precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
# frontier primitives
fp-evm = { workspace = true }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
]
