[package]
name = "fp-consensus"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "Primitives for Frontier consensus."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ethereum = { version = "0.14.0", default-features = false, features = ["with-codec"] }

# Parity
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }

# Substrate
sp-core = { version = "7.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { version = "7.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"ethereum/std",
	# Parity
	"codec/std",
	# Substrate
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
