[package]
name = "fp-consensus"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "Primitives for Frontier consensus."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
ethereum = { workspace = true }

# substrate primitives
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum/std",
	# substrate primitives
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
