[package]
name = "fp-rpc"
version = "3.0.0-dev"
license = "Apache-2.0"
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
ethereum = { workspace = true }
ethereum-types = { workspace = true }
scale-info = { workspace = true }

# substrate primitives
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# frontier
fp-evm = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
	"scale-info/std",
	# substrate primitives
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	# frontier
	"fp-evm/std",
]
