[package]
name = "fp-evm"
version = "3.0.0-dev"
license = "Apache-2.0"
description = "Primitive EVM abstractions for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
evm = { workspace = true, features = ["with-codec"] }
serde = { workspace = true, optional = true }
# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"evm/std",
	"evm/with-serde",
	"serde",
	# Substrate
	"frame-support/std",
	"sp-core/std",
	"sp-std/std",
]
