[package]
name = "fp-evm"
version = "3.0.0-dev"
license = "Apache-2.0"
description = "Primitive EVM abstractions for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
evm = { workspace = true }
serde = { workspace = true, optional = true }

# substrate primitives
sp-core = { workspace = true }
sp-std = { workspace = true }
# substrate frame
frame-support = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"evm/std",
	"evm/with-serde",
	"serde",
	# substrate primitives
	"sp-core/std",
	"sp-std/std",
	# substrate frame
	"frame-support/std",
]
