[package]
name = "fp-ethereum"
version = "1.0.0-dev"
license = "Apache-2.0"
description = "Primitive Ethereum types."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
ethereum = { workspace = true }
ethereum-types = { workspace = true }
num_enum = { version = "0.5.4", default-features = false }

# substrate primitives
sp-core = { workspace = true }
sp-std = { workspace = true }
# substrate frame
frame-support = { workspace = true }

# frontier
fp-evm = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
	"num_enum/std",
	# substrate primitives
	"sp-core/std",
	"sp-std/std",
	# substrate frame
	"frame-support/std",
	# frontier
	"fp-evm/std",
]
