[package]
name = "pallet-evm-precompile-dispatch"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "DISPATCH precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
# substrate frame
frame-support = { workspace = true }

# frontier primitives
fp-evm = { workspace = true }
# frontier frame
pallet-evm = { workspace = true }

[dev-dependencies]
codec = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }

# substrate primitives
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
# substrate frame
frame-system = { workspace = true }
pallet-balances = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true }
pallet-utility = { workspace = true }

[features]
default = ["std"]
std = [
	# substrate frame
	"frame-support/std",
	# frontier primitives
	"fp-evm/std",
	# frontier frame
	"pallet-evm/std",
]
