[package]
name = "pallet-evm-precompile-bn128"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "BN128 precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
bn = { workspace = true }

# substrate primitives
sp-core = { workspace = true }

# frontier primitives
fp-evm = { workspace = true }

[dev-dependencies]
pallet-evm-test-vector-support = { workspace = true }

[features]
default = ["std"]
std = [
	# substrate primitives
	"sp-core/std",
	# frontier primitives
	"fp-evm/std",
]
