[package]
name = "pallet-evm-test-vector-support"
version = "1.0.0-dev"
license = "Apache-2.0"
description = "Test vector support for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
evm = { workspace = true, features = ["with-codec"] }
hex = "0.4.3"
serde = { workspace = true }
serde_json = { workspace = true }

# substrate primitives
sp-core = { version = "7.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

# frontier primitives
fp-evm = { version = "3.0.0-dev", path = "../../../primitives/evm" }
