name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Run Rust tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly-2022-05-02]
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        target: wasm32-unknown-unknown
        override: true
    - name: Run tests
      run: cargo test --locked --verbose --all

  integration:
    name: 'Run integration tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly-2022-05-02]
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        target: wasm32-unknown-unknown
        override: true
    - name: Build manual seal client
      run: |
        cd template/node
        cargo build --release --locked --verbose --no-default-features --features manual-seal,rpc_binary_search_estimate
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install functional tests typescript
      run: cd ts-tests && npm install
    - name: Run functional tests
      run: cd ts-tests && npm run build && npm run test

  lint:
    name: 'Run lints'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly-2022-05-02]
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt
    - name: Rustfmt
      run: cargo fmt --all -- --check
